---
apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  type: LoadBalancer
  selector:
    app: login
    version: 1.0
  ports:
      # Port accessible inside cluster
    - port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30003


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 5
  template:
    metadata:
      labels:
        app: login
        version: 1.0
    spec:
      containers:
        - name: login
          imagePullPolicy: Always
          image: aralshi/login:1.0.0
          ports:
            - containerPort: 8080
