---
apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  type: LoadBalancer
  selector:
    app: rating
  ports:
      # Port accessible inside cluster
    - port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30004


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  selector:
    matchLabels:
      app: rating
  replicas: 5
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
        - name: rating
          imagePullPolicy: Always
          image: aralshi/rating:0.0.1
          ports:
            - containerPort: 8080

