---
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: LoadBalancer
  selector:
    app: react
  ports:
      # Port accessible inside cluster
    - port: 3000
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30002


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  selector:
    matchLabels:
      app: react
  replicas: 5
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          imagePullPolicy: Always
          image: aralshi/userinterface:1.0.0
          ports:
            - containerPort: 3000

