---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  type: LoadBalancer
  selector:
    app: search
  ports:
      # Port accessible inside cluster
    - port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30001


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  selector:
    matchLabels:
      app: search
  replicas: 2
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          imagePullPolicy: Always
          image: aralshi/search:1.0.0
          ports:
            - containerPort: 8080
