---
apiVersion: v1
kind: Service
metadata:
  name: suggestion
spec:
  type: LoadBalancer
  selector:
    app: suggestion
  ports:
      # Port accessible inside cluster
    - port: 5000
      # Port to forward to inside the pod
      targetPort: 5000
      # Port accessible outside cluster
      nodePort: 30005


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suggestion
spec:
  selector:
    matchLabels:
      app: suggestion
  replicas: 5
  template:
    metadata:
      labels:
        app: suggestion
    spec:
      containers:
        - name: suggestion
          imagePullPolicy: Always
          image: aralshi/suggestion:1.0.0
          ports:
            - containerPort: 5000

